<template lang="html">
    <div id="about">
        <h1>About</h1>
        <p>Welcome on Tline!</p>
        <p>Tline allows users to create various content based on timeline concept, to showcase projects, achievements, to inspire and develop connections.</p>
        <h1>Subscription</h1>
        <p>Premium version allows to use special promotion section on the homepage. It helps you to reach more users. Number of views generated by this section is displayed on profile in form of “+100”.</p>
        <p>Additionally premium is free from ads. In these way you can eliminate advertising from your profile and timelines. For example - even non logged user visiting your profile or timeline won’t see ads.</p>
        <p>Subscription eliminates also max 2 timelines limit, you can create unlimited number. Premium users helps us to develop and improve Tline, thank you!</p>
        <h1>Coming</h1>
        <p>We are currently working on:</p>
        <ul>
            <li>Better homepage - recommendation system,</li>
            <li>More detailed statistics.</li>
        </ul>
        <h1>Regulations</h1>
        <p>Following Regulations describes the way user uses Tline. This service is created by Jakub Adamski.</p>
        <p>In Tline user can choose between two accounts - free or paid. In free version user allows to display ads from external ad networks. Tline does not transfer any additional data to advertisers and does not take responsibility for content displayed on ads. We are making everything to create smooth user experience and in case of possible violation of content rules (below) ad can be reported by user and blocked by our administrators after analyze. In free version users allow to display ads next to their content.</p>
        <p>...</p>
    </div>
</template>

<script lang="js">

  export default  {
    name: 'About',
    data () {
      return {
          baseApi: 'http://localhost:8081/api/',
      }
    },
    methods: {

    }
}


</script>

<style scoped lang="sass">
ul
    font-family: OpenSans-Regular

h1
    margin-top: 70px
    font-family: Raleway-Regular

#about
    text-align: left
    margin: 120px 20%

</style>
